include:
  - project: 'croo-dev/ci-cd-unified-template-v1.0'
    ref: v1.0.70
    file: '/kaniko.yml'
  - project: 'croo-dev/ci-cd-unified-template-v1.0'
    ref: v1.0.70
    file: '/templates/parent.yml'

default:
  tags: [k8s]

variables:
  CICD_TEMPLATES_REF: "v1.0.70"
  DEPLOY_BRANCH: "develop"
