# Production environment values for frontend

deployment:
  replicas: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  ENVIRONMENT: production
  API_BASE_URL: "https://cde.croo.io/api"

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

imagePullSecrets:
  enabled: true
