env: dev
host: ''
ingressClassName: nginx
tls:
  secretName: wildcard-tls
  sourceSecretName: ''
  sourceNamespace: cert-manager
  enableCopyJob: false
routes:
  apis:
  - name: auth
    service: auth-b4f-api
  - name: crm
    service: crm-b4f-api
  - name: agent-control
    service: agent-control-b4f-api
  - name: communication
    service: communication-b4f-api
  - name: platform
    service: platform-b4f-api
  - name: bob-settings
    service: platform-b4f-api
  - name: kb
    service: kb-b4f-api
  - name: bob-chat
    service: bob-chat-b4f-api
  frontend:
    enabled: true
    service: frontend
    port: 80
annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/proxy-body-size: 50m
  nginx.ingress.kubernetes.io/proxy-connect-timeout: '60'
  nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
  nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
  nginx.ingress.kubernetes.io/use-regex: 'true'
  nginx.ingress.kubernetes.io/rewrite-target: /$2
