apiName: platform-b4f-api
apiTier: exposed
replicaCount: 1
service:
  targetPort: 8005
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
config:
  ENVIRONMENT: development
  LOG_LEVEL: DEBUG
  LOG_FORMAT: json
  PORT: '8005'
  API_PORT: '8005'
  BOB_CLOUD_MODE: stub
  BOB_CLOUD_STUB_API_URL: http://bob-cloud-stub-api:8010
secretRefs:
- name: b4f-runtime-secrets
initContainers:
  migrate:
    enabled: false
