"""initial_schema

Revision ID: 281cc4ea76c7
Revises: 
Create Date: 2026-03-08 09:30:13.289627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281cc4ea76c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_articles_category_id'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_is_deleted'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_is_published'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_slug'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_tenant_id'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_visibility'), table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index(op.f('ix_kb_categories_slug'), table_name='kb_categories')
    op.drop_index(op.f('ix_kb_categories_tenant_id'), table_name='kb_categories')
    op.drop_table('kb_categories')
    op.create_index(op.f('ix_bcc_roles_team_id'), 'bcc_roles', ['team_id'], unique=False)
    op.alter_column('bcc_skills', 'training_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bcc_tasks', 'training_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('organizations', 'organization_profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Deep enrichment profile (services, contacts, social, etc.)',
               existing_nullable=True)
    op.alter_column('users', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'trust_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.1'))
    op.alter_column('organizations', 'organization_profile',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Deep enrichment profile (services, contacts, social, etc.)',
               existing_nullable=True)
    op.alter_column('bcc_tasks', 'training_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bcc_skills', 'training_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_bcc_roles_team_id'), table_name='bcc_roles')
    op.create_table('kb_categories',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_categories_pkey'))
    )
    op.create_index(op.f('ix_kb_categories_tenant_id'), 'kb_categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kb_categories_slug'), 'kb_categories', ['slug'], unique=False)
    op.create_table('kb_articles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('visibility', postgresql.ENUM('INTERNAL', 'SHARED', 'PUBLIC', name='articlevisibility'), autoincrement=False, nullable=False),
    sa.Column('required_module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('required_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('author_role', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('author_avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('read_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('helpful_yes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('helpful_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('deleted_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['kb_categories.id'], name=op.f('kb_articles_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_articles_pkey'))
    )
    op.create_index(op.f('ix_kb_articles_visibility'), 'kb_articles', ['visibility'], unique=False)
    op.create_index(op.f('ix_kb_articles_tenant_id'), 'kb_articles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kb_articles_slug'), 'kb_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_kb_articles_is_published'), 'kb_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_kb_articles_is_deleted'), 'kb_articles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_kb_articles_category_id'), 'kb_articles', ['category_id'], unique=False)
    # ### end Alembic commands ###
