"""initial tables

Revision ID: 9e7b6d69658d
Revises: 
Create Date: 2026-03-24 13:02:05.334562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7b6d69658d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_rate_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.Enum('LLM', 'STT', 'TTS', 'VOIP', 'SEARCH', 'ENRICHMENT', 'WORKFLOW', 'TOOL', 'RETRIEVAL', name='servicetype'), nullable=False),
    sa.Column('unit_type', sa.Enum('INPUT_TOKEN', 'OUTPUT_TOKEN', 'SECOND', 'CHARACTER', 'MINUTE', name='rateunittype'), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=18, scale=12), nullable=False, comment='Cost per unit in currency'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='NULL = currently active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_rate_cards_model'), 'cost_rate_cards', ['model'], unique=False)
    op.create_index(op.f('ix_cost_rate_cards_provider'), 'cost_rate_cards', ['provider'], unique=False)
    op.create_table('usage_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('service_type', sa.Enum('LLM', 'STT', 'TTS', 'VOIP', 'SEARCH', 'ENRICHMENT', 'WORKFLOW', 'TOOL', 'RETRIEVAL', name='servicetype'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('billing_category', sa.Enum('AI_USAGE', 'VOICE', 'DATA', 'AUTOMATION', name='billingcategory'), nullable=False),
    sa.Column('trigger_source', sa.Enum('BOB_CHAT', 'BOB_VOICE', 'WORKFLOW', 'ENRICHMENT', 'API', 'SYSTEM', name='triggersource'), nullable=False),
    sa.Column('trigger_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_label', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Float(), nullable=True),
    sa.Column('characters', sa.Integer(), nullable=True),
    sa.Column('voip_minutes', sa.Float(), nullable=True),
    sa.Column('cogs_amount', sa.Numeric(precision=12, scale=6), nullable=True, comment='Calculated supplier cost'),
    sa.Column('cogs_currency', sa.String(length=3), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='tool_name, skill, step_name, etc.'),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_transactions_billing_category'), 'usage_transactions', ['billing_category'], unique=False)
    op.create_index(op.f('ix_usage_transactions_correlation_id'), 'usage_transactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_usage_transactions_service_type'), 'usage_transactions', ['service_type'], unique=False)
    op.create_index(op.f('ix_usage_transactions_tenant_id'), 'usage_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_transactions_timestamp'), 'usage_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_transactions_trigger_source'), 'usage_transactions', ['trigger_source'], unique=False)
    op.create_index(op.f('ix_usage_transactions_user_id'), 'usage_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='email'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='kb'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='activity'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='agent'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='product'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='org'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='opportunity'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='contact'
    )
    op.drop_index(op.f('ix_usage_transactions_user_id'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_trigger_source'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_timestamp'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_tenant_id'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_service_type'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_correlation_id'), table_name='usage_transactions')
    op.drop_index(op.f('ix_usage_transactions_billing_category'), table_name='usage_transactions')
    op.drop_table('usage_transactions')
    op.drop_index(op.f('ix_cost_rate_cards_provider'), table_name='cost_rate_cards')
    op.drop_index(op.f('ix_cost_rate_cards_model'), table_name='cost_rate_cards')
    op.drop_table('cost_rate_cards')
    # ### end Alembic commands ###
