"""initial tables

Revision ID: 3a44e84b2d48
Revises: 
Create Date: 2026-03-24 13:02:01.570818

"""
from typing import Sequence, Union
import os

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a44e84b2d48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA_NAME = 'email'


def _quoted_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _grant_schema_privileges() -> None:
    db_user = os.environ.get("DB_USERNAME")
    if not db_user:
        return
    schema = _quoted_identifier(SCHEMA_NAME)
    user = _quoted_identifier(db_user)
    op.execute(f"GRANT USAGE, CREATE ON SCHEMA {schema} TO {user}")
    op.execute(f"GRANT ALL ON ALL TABLES IN SCHEMA {schema} TO {user}")
    op.execute(f"GRANT ALL ON ALL SEQUENCES IN SCHEMA {schema} TO {user}")
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT ALL ON TABLES TO {user}")
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT ALL ON SEQUENCES TO {user}")


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_quoted_identifier(SCHEMA_NAME)}")
    op.execute(f"SET search_path TO {_quoted_identifier(SCHEMA_NAME)}")
    _grant_schema_privileges()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms365_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('ms_user_id', sa.String(length=255), nullable=True, comment='Microsoft user object ID'),
    sa.Column('ms_email', sa.String(length=255), nullable=True, comment='Microsoft email address'),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True, comment='Granted OAuth scopes, space-separated'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_email_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_calendar_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_delta_token', sa.Text(), nullable=True, comment='MS Graph delta token for emails'),
    sa.Column('calendar_delta_token', sa.Text(), nullable=True, comment='MS Graph delta token for calendar'),
    sa.Column('email_webhook_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('email_webhook_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_webhook_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('calendar_webhook_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ms365_connections_is_deleted'), 'ms365_connections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ms365_connections_tenant_id'), 'ms365_connections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ms365_connections_user_id'), 'ms365_connections', ['user_id'], unique=True)
    op.create_table('smart_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='List of keywords for matching'),
    sa.Column('prompt_hint', sa.Text(), nullable=True, comment='LLM hint for classification'),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['smart_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_labels_name'), 'smart_labels', ['name'], unique=False)
    op.create_index(op.f('ix_smart_labels_parent_id'), 'smart_labels', ['parent_id'], unique=False)
    op.create_index(op.f('ix_smart_labels_tenant_id'), 'smart_labels', ['tenant_id'], unique=False)
    op.create_table('synced_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ms365_connection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('ms_message_id', sa.String(length=255), nullable=False, comment='MS Graph message ID'),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=True, comment='List of {address, name} dicts'),
    sa.Column('cc_addresses', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachments_meta', sa.JSON(), nullable=True, comment='List of {name, size, contentType} dicts'),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('smart_label', sa.String(length=50), nullable=True, comment='AI-assigned category'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='Short AI-generated summary of email content'),
    sa.Column('ai_action_items', sa.JSON(), nullable=True, comment='List of action items extracted by AI'),
    sa.Column('conversation_id', sa.String(length=255), nullable=True, comment='MS Graph conversation ID for threading'),
    sa.Column('linked_contact_id', sa.String(length=36), nullable=True, comment='Soft ref to contact-backend-api contacts.id'),
    sa.Column('linked_organization_id', sa.String(length=36), nullable=True, comment='Soft ref to org-backend-api organizations.id'),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ms365_connection_id'], ['ms365_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synced_emails_conversation_id'), 'synced_emails', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_synced_emails_folder'), 'synced_emails', ['folder'], unique=False)
    op.create_index(op.f('ix_synced_emails_from_address'), 'synced_emails', ['from_address'], unique=False)
    op.create_index(op.f('ix_synced_emails_linked_contact_id'), 'synced_emails', ['linked_contact_id'], unique=False)
    op.create_index(op.f('ix_synced_emails_linked_organization_id'), 'synced_emails', ['linked_organization_id'], unique=False)
    op.create_index(op.f('ix_synced_emails_ms365_connection_id'), 'synced_emails', ['ms365_connection_id'], unique=False)
    op.create_index(op.f('ix_synced_emails_ms_message_id'), 'synced_emails', ['ms_message_id'], unique=True)
    op.create_index(op.f('ix_synced_emails_received_at'), 'synced_emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_synced_emails_smart_label'), 'synced_emails', ['smart_label'], unique=False)
    op.create_index(op.f('ix_synced_emails_subject'), 'synced_emails', ['subject'], unique=False)
    op.create_index(op.f('ix_synced_emails_tenant_id'), 'synced_emails', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_synced_emails_user_id'), 'synced_emails', ['user_id'], unique=False)
    op.create_table('synced_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ms365_connection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('ms_event_id', sa.String(length=255), nullable=False, comment='MS Graph event ID'),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('organizer_name', sa.String(length=255), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True, comment='List of {email, name, status} dicts'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='User response: accepted/tentative/declined/none'),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.JSON(), nullable=True, comment='Recurrence pattern from MS Graph'),
    sa.Column('online_meeting_url', sa.Text(), nullable=True, comment='Teams/Zoom meeting link'),
    sa.Column('linked_contact_id', sa.String(length=36), nullable=True, comment='Soft ref to contact-backend-api contacts.id'),
    sa.Column('linked_organization_id', sa.String(length=36), nullable=True, comment='Soft ref to org-backend-api organizations.id'),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ms365_connection_id'], ['ms365_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synced_events_linked_contact_id'), 'synced_events', ['linked_contact_id'], unique=False)
    op.create_index(op.f('ix_synced_events_linked_organization_id'), 'synced_events', ['linked_organization_id'], unique=False)
    op.create_index(op.f('ix_synced_events_ms365_connection_id'), 'synced_events', ['ms365_connection_id'], unique=False)
    op.create_index(op.f('ix_synced_events_ms_event_id'), 'synced_events', ['ms_event_id'], unique=True)
    op.create_index(op.f('ix_synced_events_organizer_email'), 'synced_events', ['organizer_email'], unique=False)
    op.create_index(op.f('ix_synced_events_start_time'), 'synced_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_synced_events_subject'), 'synced_events', ['subject'], unique=False)
    op.create_index(op.f('ix_synced_events_tenant_id'), 'synced_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_synced_events_user_id'), 'synced_events', ['user_id'], unique=False)
    op.create_table('email_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('synced_email_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False, comment='from | to | cc'),
    sa.ForeignKeyConstraint(['synced_email_id'], ['synced_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_contacts_contact_id'), 'email_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_contacts_synced_email_id'), 'email_contacts', ['synced_email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(f"SET search_path TO {_quoted_identifier(SCHEMA_NAME)}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_contacts_synced_email_id'), table_name='email_contacts')
    op.drop_index(op.f('ix_email_contacts_contact_id'), table_name='email_contacts')
    op.drop_table('email_contacts')
    op.drop_index(op.f('ix_synced_events_user_id'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_tenant_id'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_subject'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_start_time'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_organizer_email'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_ms_event_id'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_ms365_connection_id'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_linked_organization_id'), table_name='synced_events')
    op.drop_index(op.f('ix_synced_events_linked_contact_id'), table_name='synced_events')
    op.drop_table('synced_events')
    op.drop_index(op.f('ix_synced_emails_user_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_tenant_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_subject'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_smart_label'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_received_at'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_ms_message_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_ms365_connection_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_linked_organization_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_linked_contact_id'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_from_address'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_folder'), table_name='synced_emails')
    op.drop_index(op.f('ix_synced_emails_conversation_id'), table_name='synced_emails')
    op.drop_table('synced_emails')
    op.drop_index(op.f('ix_smart_labels_tenant_id'), table_name='smart_labels')
    op.drop_index(op.f('ix_smart_labels_parent_id'), table_name='smart_labels')
    op.drop_index(op.f('ix_smart_labels_name'), table_name='smart_labels')
    op.drop_table('smart_labels')
    op.drop_index(op.f('ix_ms365_connections_user_id'), table_name='ms365_connections')
    op.drop_index(op.f('ix_ms365_connections_tenant_id'), table_name='ms365_connections')
    op.drop_index(op.f('ix_ms365_connections_is_deleted'), table_name='ms365_connections')
    op.drop_table('ms365_connections')
    op.execute(f"DROP SCHEMA IF EXISTS {_quoted_identifier(SCHEMA_NAME)} CASCADE")
    # ### end Alembic commands ###
