"""initial tables

Revision ID: 49535a767d77
Revises: 
Create Date: 2026-03-24 13:02:00.135903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49535a767d77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bcc_careers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('typical_skills', sa.JSON(), nullable=True),
    sa.Column('typical_tasks', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_careers_tenant_id'), 'bcc_careers', ['tenant_id'], unique=False)
    op.create_table('bcc_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_domains_tenant_id'), 'bcc_domains', ['tenant_id'], unique=False)
    op.create_table('bcc_industries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('best_practices', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_industries_tenant_id'), 'bcc_industries', ['tenant_id'], unique=False)
    op.create_table('bcc_organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_organizations_tenant_id'), 'bcc_organizations', ['tenant_id'], unique=False)
    op.create_table('bcc_profile_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('perspective', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contributed_by', sa.String(length=36), nullable=True),
    sa.Column('contributor_name', sa.String(length=200), nullable=True),
    sa.Column('contribution_method', sa.String(length=20), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_profile_entries_entity_id'), 'bcc_profile_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_bcc_profile_entries_entity_type'), 'bcc_profile_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_bcc_profile_entries_section'), 'bcc_profile_entries', ['section'], unique=False)
    op.create_index(op.f('ix_bcc_profile_entries_tenant_id'), 'bcc_profile_entries', ['tenant_id'], unique=False)
    op.create_table('bcc_skill_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_skill_templates_tenant_id'), 'bcc_skill_templates', ['tenant_id'], unique=False)
    op.create_table('bcc_task_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('required_skill_ids', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_task_templates_tenant_id'), 'bcc_task_templates', ['tenant_id'], unique=False)
    op.create_table('bob_user_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('formality', sa.Float(), nullable=False),
    sa.Column('response_length', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('emoji_usage', sa.Boolean(), nullable=False),
    sa.Column('voice', sa.String(length=30), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('auto_listen', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bob_user_settings_tenant_id'), 'bob_user_settings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bob_user_settings_user_id'), 'bob_user_settings', ['user_id'], unique=True)
    op.create_table('capability_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_definitions_code'), 'capability_definitions', ['code'], unique=True)
    op.create_table('client_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('role_type', sa.Enum('DECISION_MAKER', 'INFLUENCER', 'USER', 'CHAMPION', 'BLOCKER', 'GATEKEEPER', name='roletype'), nullable=True),
    sa.Column('real_role', sa.String(length=200), nullable=True),
    sa.Column('disc_profile', sa.Enum('D', 'I', 'S', 'C', 'UNKNOWN', name='discprofile'), nullable=True),
    sa.Column('ecosystem_tools', sa.JSON(), nullable=True, comment="e.g. ['Salesforce', 'Excel']"),
    sa.Column('ecosystem_partners', sa.JSON(), nullable=True, comment='Partners and competitors'),
    sa.Column('company_culture', sa.Enum('CONSERVATIVE', 'INNOVATIVE', 'COST_OBSESSED', 'AGILE', 'BUREAUCRATIC', name='companyculture'), nullable=True),
    sa.Column('pain_point', sa.Text(), nullable=True, comment="Le 'mal de dent' — surface pain"),
    sa.Column('pain_business_impact', sa.Text(), nullable=True, comment='Level 2 — business consequence'),
    sa.Column('pain_personal_impact', sa.Text(), nullable=True, comment='Level 3 — personal/emotional impact'),
    sa.Column('inaction_cost', sa.Text(), nullable=True, comment='What happens in 6 months if nothing changes'),
    sa.Column('trigger_event', sa.Text(), nullable=True, comment='Why are they talking to us NOW'),
    sa.Column('trigger_type', sa.Enum('MERGER', 'NEW_BUDGET', 'CRISIS', 'CONTRACT_END', 'LEADERSHIP_CHANGE', 'COMPETITOR_MOVE', 'REGULATION', 'OTHER', name='triggertype'), nullable=True),
    sa.Column('metrics_target', sa.Text(), nullable=True, comment='M of MEDDPICC — targeted quantified gain'),
    sa.Column('wiifm_business', sa.Text(), nullable=True, comment='ROI, productivity, market share'),
    sa.Column('wiifm_personal', sa.Text(), nullable=True, comment='Promotion, stress, work-life — the trust field'),
    sa.Column('success_vision', sa.Text(), nullable=True, comment='Perfect win in 1 year'),
    sa.Column('ego_driver', sa.Enum('RECOGNITION', 'SECURITY', 'TIME', 'POWER', 'LEGACY', name='egodriver'), nullable=True, comment='What makes them shine to their boss'),
    sa.Column('economic_buyer', sa.Text(), nullable=True, comment='E of MEDDPICC — who signs the check'),
    sa.Column('decision_criteria', sa.Text(), nullable=True, comment='D — technical/financial criteria'),
    sa.Column('decision_process', sa.Text(), nullable=True, comment='D — internal validation steps'),
    sa.Column('paper_process', sa.Text(), nullable=True, comment='P — legal/procurement workflow'),
    sa.Column('champion_name', sa.Text(), nullable=True, comment='C — internal ally'),
    sa.Column('competition', sa.Text(), nullable=True, comment='C — who else is being evaluated'),
    sa.Column('alternative_if_no', sa.Text(), nullable=True, comment="What do they do if they don't sign"),
    sa.Column('blockers', sa.Text(), nullable=True, comment='Fear of change, unallocated budget, politics'),
    sa.Column('timeline_real', sa.Text(), nullable=True, comment='Real deadlines'),
    sa.Column('timeline_wished', sa.Text(), nullable=True, comment='Wished deadlines'),
    sa.Column('trust_level', sa.Integer(), nullable=True, comment='1-5 trust indicator'),
    sa.Column('meddpicc_score', sa.Integer(), nullable=True, comment='0-100 MEDDPICC completeness'),
    sa.Column('behavioral_profile', sa.JSON(), nullable=True, comment='AI-computed behavioral analysis'),
    sa.Column('last_behavioral_analysis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_maps_contact_id'), 'client_maps', ['contact_id'], unique=True)
    op.create_index(op.f('ix_client_maps_is_deleted'), 'client_maps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_client_maps_tenant_id'), 'client_maps', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('training_slug', sa.String(length=100), nullable=False),
    sa.Column('current_slide', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_tenant_id'), 'training_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_training_slug'), 'training_sessions', ['training_slug'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('bcc_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['bcc_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_departments_organization_id'), 'bcc_departments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bcc_departments_tenant_id'), 'bcc_departments', ['tenant_id'], unique=False)
    op.create_table('bcc_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_phrases', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('domain_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_key', sa.String(length=100), nullable=True),
    sa.Column('pipeline_key', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['bcc_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_intents_tenant_id'), 'bcc_intents', ['tenant_id'], unique=False)
    op.create_table('bcc_org_industries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('industry_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['industry_id'], ['bcc_industries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['bcc_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_org_industries_industry_id'), 'bcc_org_industries', ['industry_id'], unique=False)
    op.create_index(op.f('ix_bcc_org_industries_organization_id'), 'bcc_org_industries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bcc_org_industries_tenant_id'), 'bcc_org_industries', ['tenant_id'], unique=False)
    op.create_table('bcc_org_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('operations_domains', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['bcc_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_org_profiles_organization_id'), 'bcc_org_profiles', ['organization_id'], unique=True)
    op.create_index(op.f('ix_bcc_org_profiles_tenant_id'), 'bcc_org_profiles', ['tenant_id'], unique=False)
    op.create_table('dept_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_definitions.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dept_capabilities_capability_id'), 'dept_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_dept_capabilities_department_id'), 'dept_capabilities', ['department_id'], unique=False)
    op.create_index(op.f('ix_dept_capabilities_tenant_id'), 'dept_capabilities', ['tenant_id'], unique=False)
    op.create_table('golden_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_map_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interaction_type', sa.Enum('CALL', 'MEETING', 'EMAIL', 'DEMO', 'QBR', 'SOCIAL', name='interactiontype'), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=True, comment='Exact client quote — persuasion weapon'),
    sa.Column('silence_observed', sa.Text(), nullable=True, comment='What was NOT said but felt'),
    sa.Column('emotional_climate', sa.Enum('DEFENSIVE', 'ENTHUSIASTIC', 'RUSHED', 'TIRED', 'NEUTRAL', 'CONFIDENT', 'FRUSTRATED', 'CURIOUS', 'HESITANT', name='emotionalclimate'), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True, comment='Concrete action the client agreed to'),
    sa.Column('next_step_owner', sa.Enum('US', 'CLIENT', 'BOTH', name='nextstepowner'), nullable=True),
    sa.Column('next_step_deadline', sa.Date(), nullable=True),
    sa.Column('ai_extracted_insights', sa.JSON(), nullable=True, comment='Auto-parsed triples by Bob'),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_map_id'], ['client_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_notes_client_map_id'), 'golden_notes', ['client_map_id'], unique=False)
    op.create_index(op.f('ix_golden_notes_is_deleted'), 'golden_notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_golden_notes_tenant_id'), 'golden_notes', ['tenant_id'], unique=False)
    op.create_table('training_missing_elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_missing_elements_session_id'), 'training_missing_elements', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_missing_elements_tenant_id'), 'training_missing_elements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_missing_elements_user_id'), 'training_missing_elements', ['user_id'], unique=False)
    op.create_table('training_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_notes_session_id'), 'training_notes', ['session_id'], unique=False)
    op.create_index(op.f('ix_training_notes_tenant_id'), 'training_notes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_notes_user_id'), 'training_notes', ['user_id'], unique=False)
    op.create_table('user_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_capabilities_capability_id'), 'user_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_user_capabilities_tenant_id'), 'user_capabilities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_capabilities_user_id'), 'user_capabilities', ['user_id'], unique=False)
    op.create_table('user_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('is_manager', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_departments_department_id'), 'user_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_departments_user_id'), 'user_departments', ['user_id'], unique=False)
    op.create_table('bcc_intent_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('task_template_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['intent_id'], ['bcc_intents.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['bcc_task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_intent_tasks_tenant_id'), 'bcc_intent_tasks', ['tenant_id'], unique=False)
    op.create_table('bcc_regulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('enforcement_level', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['bcc_org_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_regulations_profile_id'), 'bcc_regulations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_bcc_regulations_tenant_id'), 'bcc_regulations', ['tenant_id'], unique=False)
    op.create_table('bcc_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['bcc_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_teams_department_id'), 'bcc_teams', ['department_id'], unique=False)
    op.create_index(op.f('ix_bcc_teams_tenant_id'), 'bcc_teams', ['tenant_id'], unique=False)
    op.create_table('insight_triples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_map_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False, comment='CONTACT, ORGANIZATION, OPPORTUNITY'),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('predicate', sa.Enum('HAS_PAIN', 'FEARS', 'WANTS', 'BLOCKS', 'INFLUENCES', 'USES', 'COMPETES_WITH', 'REPORTS_TO', 'CHAMPIONS', name='insightpredicate'), nullable=False),
    sa.Column('object_value', sa.Text(), nullable=False),
    sa.Column('object_entity_id', sa.String(length=36), nullable=True, comment='If target is a CRM entity'),
    sa.Column('depth_level', sa.Enum('SURFACE', 'BUSINESS', 'PERSONAL', name='depthlevel'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True, comment='0-1 confidence score'),
    sa.Column('source', sa.Enum('MANUAL', 'AI_PARSED', 'BOB_INFERRED', name='insightsource'), nullable=True),
    sa.Column('source_note_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_map_id'], ['client_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_note_id'], ['golden_notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_triples_client_map_id'), 'insight_triples', ['client_map_id'], unique=False)
    op.create_index(op.f('ix_insight_triples_tenant_id'), 'insight_triples', ['tenant_id'], unique=False)
    op.create_table('bcc_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['bcc_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_roles_team_id'), 'bcc_roles', ['team_id'], unique=False)
    op.create_index(op.f('ix_bcc_roles_tenant_id'), 'bcc_roles', ['tenant_id'], unique=False)
    op.create_table('bcc_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_milestones_role_id'), 'bcc_milestones', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_milestones_tenant_id'), 'bcc_milestones', ['tenant_id'], unique=False)
    op.create_table('bcc_role_careers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('career_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['career_id'], ['bcc_careers.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_role_careers_career_id'), 'bcc_role_careers', ['career_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_careers_role_id'), 'bcc_role_careers', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_careers_tenant_id'), 'bcc_role_careers', ['tenant_id'], unique=False)
    op.create_table('bcc_role_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('skill_template_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.ForeignKeyConstraint(['skill_template_id'], ['bcc_skill_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_role_skills_role_id'), 'bcc_role_skills', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_skills_skill_template_id'), 'bcc_role_skills', ['skill_template_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_skills_tenant_id'), 'bcc_role_skills', ['tenant_id'], unique=False)
    op.create_table('bcc_role_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('task_template_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['bcc_task_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_role_tasks_role_id'), 'bcc_role_tasks', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_tasks_task_template_id'), 'bcc_role_tasks', ['task_template_id'], unique=False)
    op.create_index(op.f('ix_bcc_role_tasks_tenant_id'), 'bcc_role_tasks', ['tenant_id'], unique=False)
    op.create_table('bcc_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('training_data', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_skills_role_id'), 'bcc_skills', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_skills_tenant_id'), 'bcc_skills', ['tenant_id'], unique=False)
    op.create_table('bcc_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('training_data', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_tasks_role_id'), 'bcc_tasks', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_tasks_tenant_id'), 'bcc_tasks', ['tenant_id'], unique=False)
    op.create_table('bcc_user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['bcc_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_user_roles_role_id'), 'bcc_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_roles_tenant_id'), 'bcc_user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_roles_user_id'), 'bcc_user_roles', ['user_id'], unique=False)
    op.create_table('bcc_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['bcc_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_resources_skill_id'), 'bcc_resources', ['skill_id'], unique=False)
    op.create_index(op.f('ix_bcc_resources_tenant_id'), 'bcc_resources', ['tenant_id'], unique=False)
    op.create_table('bcc_task_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['bcc_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_task_steps_task_id'), 'bcc_task_steps', ['task_id'], unique=False)
    op.create_table('bcc_user_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('skill_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['bcc_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_user_progress_skill_id'), 'bcc_user_progress', ['skill_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_progress_tenant_id'), 'bcc_user_progress', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_progress_user_id'), 'bcc_user_progress', ['user_id'], unique=False)
    op.create_table('bcc_user_task_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Soft ref to user-backend-api users.id'),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['bcc_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bcc_user_task_logs_task_id'), 'bcc_user_task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_task_logs_tenant_id'), 'bcc_user_task_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bcc_user_task_logs_user_id'), 'bcc_user_task_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='activity'
    )
    op.drop_index(op.f('ix_bcc_user_task_logs_user_id'), table_name='bcc_user_task_logs')
    op.drop_index(op.f('ix_bcc_user_task_logs_tenant_id'), table_name='bcc_user_task_logs')
    op.drop_index(op.f('ix_bcc_user_task_logs_task_id'), table_name='bcc_user_task_logs')
    op.drop_table('bcc_user_task_logs')
    op.drop_index(op.f('ix_bcc_user_progress_user_id'), table_name='bcc_user_progress')
    op.drop_index(op.f('ix_bcc_user_progress_tenant_id'), table_name='bcc_user_progress')
    op.drop_index(op.f('ix_bcc_user_progress_skill_id'), table_name='bcc_user_progress')
    op.drop_table('bcc_user_progress')
    op.drop_index(op.f('ix_bcc_task_steps_task_id'), table_name='bcc_task_steps')
    op.drop_table('bcc_task_steps')
    op.drop_index(op.f('ix_bcc_resources_tenant_id'), table_name='bcc_resources')
    op.drop_index(op.f('ix_bcc_resources_skill_id'), table_name='bcc_resources')
    op.drop_table('bcc_resources')
    op.drop_index(op.f('ix_bcc_user_roles_user_id'), table_name='bcc_user_roles')
    op.drop_index(op.f('ix_bcc_user_roles_tenant_id'), table_name='bcc_user_roles')
    op.drop_index(op.f('ix_bcc_user_roles_role_id'), table_name='bcc_user_roles')
    op.drop_table('bcc_user_roles')
    op.drop_index(op.f('ix_bcc_tasks_tenant_id'), table_name='bcc_tasks')
    op.drop_index(op.f('ix_bcc_tasks_role_id'), table_name='bcc_tasks')
    op.drop_table('bcc_tasks')
    op.drop_index(op.f('ix_bcc_skills_tenant_id'), table_name='bcc_skills')
    op.drop_index(op.f('ix_bcc_skills_role_id'), table_name='bcc_skills')
    op.drop_table('bcc_skills')
    op.drop_index(op.f('ix_bcc_role_tasks_tenant_id'), table_name='bcc_role_tasks')
    op.drop_index(op.f('ix_bcc_role_tasks_task_template_id'), table_name='bcc_role_tasks')
    op.drop_index(op.f('ix_bcc_role_tasks_role_id'), table_name='bcc_role_tasks')
    op.drop_table('bcc_role_tasks')
    op.drop_index(op.f('ix_bcc_role_skills_tenant_id'), table_name='bcc_role_skills')
    op.drop_index(op.f('ix_bcc_role_skills_skill_template_id'), table_name='bcc_role_skills')
    op.drop_index(op.f('ix_bcc_role_skills_role_id'), table_name='bcc_role_skills')
    op.drop_table('bcc_role_skills')
    op.drop_index(op.f('ix_bcc_role_careers_tenant_id'), table_name='bcc_role_careers')
    op.drop_index(op.f('ix_bcc_role_careers_role_id'), table_name='bcc_role_careers')
    op.drop_index(op.f('ix_bcc_role_careers_career_id'), table_name='bcc_role_careers')
    op.drop_table('bcc_role_careers')
    op.drop_index(op.f('ix_bcc_milestones_tenant_id'), table_name='bcc_milestones')
    op.drop_index(op.f('ix_bcc_milestones_role_id'), table_name='bcc_milestones')
    op.drop_table('bcc_milestones')
    op.drop_index(op.f('ix_bcc_roles_tenant_id'), table_name='bcc_roles')
    op.drop_index(op.f('ix_bcc_roles_team_id'), table_name='bcc_roles')
    op.drop_table('bcc_roles')
    op.drop_index(op.f('ix_insight_triples_tenant_id'), table_name='insight_triples')
    op.drop_index(op.f('ix_insight_triples_client_map_id'), table_name='insight_triples')
    op.drop_table('insight_triples')
    op.drop_index(op.f('ix_bcc_teams_tenant_id'), table_name='bcc_teams')
    op.drop_index(op.f('ix_bcc_teams_department_id'), table_name='bcc_teams')
    op.drop_table('bcc_teams')
    op.drop_index(op.f('ix_bcc_regulations_tenant_id'), table_name='bcc_regulations')
    op.drop_index(op.f('ix_bcc_regulations_profile_id'), table_name='bcc_regulations')
    op.drop_table('bcc_regulations')
    op.drop_index(op.f('ix_bcc_intent_tasks_tenant_id'), table_name='bcc_intent_tasks')
    op.drop_table('bcc_intent_tasks')
    op.drop_index(op.f('ix_user_departments_user_id'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_department_id'), table_name='user_departments')
    op.drop_table('user_departments')
    op.drop_index(op.f('ix_user_capabilities_user_id'), table_name='user_capabilities')
    op.drop_index(op.f('ix_user_capabilities_tenant_id'), table_name='user_capabilities')
    op.drop_index(op.f('ix_user_capabilities_capability_id'), table_name='user_capabilities')
    op.drop_table('user_capabilities')
    op.drop_index(op.f('ix_training_notes_user_id'), table_name='training_notes')
    op.drop_index(op.f('ix_training_notes_tenant_id'), table_name='training_notes')
    op.drop_index(op.f('ix_training_notes_session_id'), table_name='training_notes')
    op.drop_table('training_notes')
    op.drop_index(op.f('ix_training_missing_elements_user_id'), table_name='training_missing_elements')
    op.drop_index(op.f('ix_training_missing_elements_tenant_id'), table_name='training_missing_elements')
    op.drop_index(op.f('ix_training_missing_elements_session_id'), table_name='training_missing_elements')
    op.drop_table('training_missing_elements')
    op.drop_index(op.f('ix_golden_notes_tenant_id'), table_name='golden_notes')
    op.drop_index(op.f('ix_golden_notes_is_deleted'), table_name='golden_notes')
    op.drop_index(op.f('ix_golden_notes_client_map_id'), table_name='golden_notes')
    op.drop_table('golden_notes')
    op.drop_index(op.f('ix_dept_capabilities_tenant_id'), table_name='dept_capabilities')
    op.drop_index(op.f('ix_dept_capabilities_department_id'), table_name='dept_capabilities')
    op.drop_index(op.f('ix_dept_capabilities_capability_id'), table_name='dept_capabilities')
    op.drop_table('dept_capabilities')
    op.drop_index(op.f('ix_bcc_org_profiles_tenant_id'), table_name='bcc_org_profiles')
    op.drop_index(op.f('ix_bcc_org_profiles_organization_id'), table_name='bcc_org_profiles')
    op.drop_table('bcc_org_profiles')
    op.drop_index(op.f('ix_bcc_org_industries_tenant_id'), table_name='bcc_org_industries')
    op.drop_index(op.f('ix_bcc_org_industries_organization_id'), table_name='bcc_org_industries')
    op.drop_index(op.f('ix_bcc_org_industries_industry_id'), table_name='bcc_org_industries')
    op.drop_table('bcc_org_industries')
    op.drop_index(op.f('ix_bcc_intents_tenant_id'), table_name='bcc_intents')
    op.drop_table('bcc_intents')
    op.drop_index(op.f('ix_bcc_departments_tenant_id'), table_name='bcc_departments')
    op.drop_index(op.f('ix_bcc_departments_organization_id'), table_name='bcc_departments')
    op.drop_table('bcc_departments')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_training_slug'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_tenant_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_client_maps_tenant_id'), table_name='client_maps')
    op.drop_index(op.f('ix_client_maps_is_deleted'), table_name='client_maps')
    op.drop_index(op.f('ix_client_maps_contact_id'), table_name='client_maps')
    op.drop_table('client_maps')
    op.drop_index(op.f('ix_capability_definitions_code'), table_name='capability_definitions')
    op.drop_table('capability_definitions')
    op.drop_index(op.f('ix_bob_user_settings_user_id'), table_name='bob_user_settings')
    op.drop_index(op.f('ix_bob_user_settings_tenant_id'), table_name='bob_user_settings')
    op.drop_table('bob_user_settings')
    op.drop_index(op.f('ix_bcc_task_templates_tenant_id'), table_name='bcc_task_templates')
    op.drop_table('bcc_task_templates')
    op.drop_index(op.f('ix_bcc_skill_templates_tenant_id'), table_name='bcc_skill_templates')
    op.drop_table('bcc_skill_templates')
    op.drop_index(op.f('ix_bcc_profile_entries_tenant_id'), table_name='bcc_profile_entries')
    op.drop_index(op.f('ix_bcc_profile_entries_section'), table_name='bcc_profile_entries')
    op.drop_index(op.f('ix_bcc_profile_entries_entity_type'), table_name='bcc_profile_entries')
    op.drop_index(op.f('ix_bcc_profile_entries_entity_id'), table_name='bcc_profile_entries')
    op.drop_table('bcc_profile_entries')
    op.drop_index(op.f('ix_bcc_organizations_tenant_id'), table_name='bcc_organizations')
    op.drop_table('bcc_organizations')
    op.drop_index(op.f('ix_bcc_industries_tenant_id'), table_name='bcc_industries')
    op.drop_table('bcc_industries')
    op.drop_index(op.f('ix_bcc_domains_tenant_id'), table_name='bcc_domains')
    op.drop_table('bcc_domains')
    op.drop_index(op.f('ix_bcc_careers_tenant_id'), table_name='bcc_careers')
    op.drop_table('bcc_careers')
    # ### end Alembic commands ###
