env: prod
host: ''
ingressClassName: nginx
tls:
  secretName: wildcard-tls
  sourceSecretName: ''
  sourceNamespace: cert-manager
  enableCopyJob: false
routes:
  apis: []
  frontend:
    enabled: true
    service: frontend
    port: 80
annotations:
  cert-manager.io/cluster-issuer: letsencrypt-http-prod
  nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  nginx.ingress.kubernetes.io/proxy-body-size: 50m
  nginx.ingress.kubernetes.io/proxy-connect-timeout: '60'
  nginx.ingress.kubernetes.io/proxy-send-timeout: '60'
  nginx.ingress.kubernetes.io/proxy-read-timeout: '60'
  nginx.ingress.kubernetes.io/use-regex: 'true'
  nginx.ingress.kubernetes.io/rewrite-target: /$2
