"""initial tables

Revision ID: 242e35bb3074
Revises: 
Create Date: 2026-03-24 13:02:02.299019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242e35bb3074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_categories_slug'), 'kb_categories', ['slug'], unique=False)
    op.create_index(op.f('ix_kb_categories_tenant_id'), 'kb_categories', ['tenant_id'], unique=False)
    op.create_table('kb_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.Enum('INTERNAL', 'SHARED', 'PUBLIC', name='articlevisibility'), nullable=False),
    sa.Column('required_module', sa.String(length=100), nullable=True),
    sa.Column('required_role', sa.String(length=50), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('author_role', sa.String(length=200), nullable=True),
    sa.Column('author_avatar', sa.String(length=500), nullable=True),
    sa.Column('read_time_minutes', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('helpful_yes', sa.Integer(), nullable=True),
    sa.Column('helpful_no', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant identifier for multi-tenant isolation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['kb_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_articles_category_id'), 'kb_articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_kb_articles_is_deleted'), 'kb_articles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_kb_articles_is_published'), 'kb_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_kb_articles_slug'), 'kb_articles', ['slug'], unique=True)
    op.create_index(op.f('ix_kb_articles_tenant_id'), 'kb_articles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_kb_articles_visibility'), 'kb_articles', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='contact'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='activity'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='agent'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc')),
    schema='email'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_kb_articles_visibility'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_tenant_id'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_slug'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_is_published'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_is_deleted'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_category_id'), table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index(op.f('ix_kb_categories_tenant_id'), table_name='kb_categories')
    op.drop_index(op.f('ix_kb_categories_slug'), table_name='kb_categories')
    op.drop_table('kb_categories')
    # ### end Alembic commands ###
