{{- if and .Values.imagePullSecrets.enabled .Values.imagePullSecrets.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-chart.imagePullSecretName" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson | b64enc }}
{{- end }}
