{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-chart.secretName" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.jwtSecret }}
  SECRET_KEY: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
{{- end }}
